name: Java Presubmit

on: [pull_request]

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Download google-java-format 1.8
        run: wget -q https://github.com/google/google-java-format/releases/download/google-java-format-1.8/google-java-format-1.8-all-deps.jar
      - name: Format with google-java-format 1.8
        # Run google-java-format on diffed Java files.
        run: |
          for file in $(git diff --name-only origin/master HEAD -- . ':!node_modules' | grep -E "(.*)\.(java)$"); do
            echo -e "Running google-java-format on:\n $file\n"
            if ! java -jar ./google-java-format-1.8-all-deps.jar $file | diff $file -; then
              EXIT=1
            fi
            echo ""
          done
          exit $EXIT
        shell: bash
